name: CI

on:
  push:
    branches: ['main']

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - run: clang -o main main.c && ./main && cargo run
